spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://postgres-prod:5432/viora_identity_prod
    hikari:
      maximum-pool-size: 30
      maximum-lifetime: 1200000
  liquibase:
    enabled: true

logging:
  level:
    root: ERROR
    com.viora: WARN
    org.springframework.security: ERROR

server:
  port: 8082
  compression:
    enabled: true
    min-response-size: 1024

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

