spring:
  data:
    mongodb:
      host: mongo-prod
      port: 27017
      database: content_prod
      auth-source: admin
      connection-string: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo-prod-cluster/content_prod

logging:
  level:
    root: ERROR
    com.viora: WARN

server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 1024

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

