spring:
  data:
    mongodb:
      host: mongo-stage
      port: 27017
      database: content_stage
      auth-source: admin

logging:
  level:
    root: WARN
    com.viora: INFO

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

