server:
  port: 8888

spring:
  application:
    name: cloud-config-service
  profiles:
    include: ${CONFIG_SERVER_BACKEND:native}
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:../${CONFIG_SEARCH_PATH:configuration}
            - file:../${CONFIG_SEARCH_PATH:configuration}/{application}
logging:
  level:
    org.springframework.cloud: TRACE
---
spring:
  config:
    activate:
      on-profile: git
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI:https://github.com/volodymyrDobry/video-streaming-api}
          clone-on-start: true
          force-pull: true