spring:
  application:
    name: identity-access
    keycloak:
      url: ${KEYCLOAK_URI:http://localhost:8080}
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/viora-dev
      client:
        registration:
          user-management-client:
            provider: keycloak
            client-id: user-management-client
            client-secret: enBnKli6dcmdMmd1PCSlKiKIReld0MNS
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URI:http://localhost:8080}/realms/viora-dev


logging:
  level:
    org.springframework.security:
    com.viora.streamingandvideo.api.controller.FileController:
      DEBUG
server:
  port: 8081
