spring:
  application:
    name: viora-streaming-gateway

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
          routes:
            - id: streaming-and-video
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/streaming/**

            - id: content-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/movies/**,/api/v1/movies
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 500
                    redis-rate-limiter.burstCapacity: 1000
                    redis-rate-limiter.requestedTokens: 1

            - id: identity-access
              uri: http://localhost:8082
              predicates:
                - Path=/api/identity/**
              filters:
                - StripPrefix=2

            - id: user-streaming-history
              uri: http://localhost:8085
              predicates:
                - Path=/api/user-history/**, /api/user-history
              filters:
                - StripPrefix=2
          metrics:
            enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI:http://localhost:8081}/realms/viora-dev

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:vovanchik_2005}


server:
  port: 8084

services:
  user-history:
    base-url: ${USER_HISTORY_SERVICE_URL:http://localhost:8085}
  content:
    base-url: ${CONTENT_SERVICE_URL:http://localhost:8080}
    movie-by-imdb-path: ${CONTENT_MOVIE_BY_IMDB_PATH:/api/v1/movies/by-imdb}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: viora-gateway

