spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: streaming-history-dev

logging:
  level:
    root: INFO
    com.viora: DEBUG

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops
  endpoint:
    health:
      show-details: always

