# Keycloak props
keycloak.url=http://localhost:8080
keycloak.realm=viora-dev
keycloak.client.id=user-management-client
keycloak.client.key=9xX4ObYEIDXHHryau8tOrUnzQxS8p4js
# application specific props
application.accounts.url=http://host.docker.internal:8082
application.accounts.register=/api/v1/admin/accounts/keycloak
