# Keycloak props
keycloak.url=http://localhost:8080
keycloak.realm=viora-dev
keycloak.client.id=admin-client
keycloak.client.key=gKZ7oP3uAvNh9rvi9DmP3oaSJWhC9rC3
# application specific props
application.accounts.url=http://host.docker.internal:8081
application.accounts.register=/api/v1/admin/accounts/keycloak
